---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure nginx as a loadbalancer
  template:
    src: nginx-lb.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Check that nginx is started
  service:
    name: nginx
    state: started

# Open port 80 for loadbalancer
- name: Check if iptables is installed
  apt:
    name: iptables
    state: present

- name: Allow port 80
  command:
    cmd: iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT 

- name: Open port 8080 in iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT

- name: Check that port 80 is open
  wait_for:
    port: 80
    timeout: 60