---
- name: Uninstall Apache2 on Debian-based systems
  apt:
    name: apache2
    state: absent

- name: Remove Apache2 configuration files on Debian-based systems
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/
    - /var/www/

- name: Remove Apache2 log files on Debian-based systems
  file:
    path: /var/log/apache2/
    state: absent
